import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('idshield-language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('idshield-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  es: {
    // Navigation
    'nav.privacy.levels': 'Niveles de Privacidad',
    'nav.demo': 'Prueba el Demo',
    'nav.use.cases': 'Casos de Uso',
    'nav.ace.framework': 'Framework ACE',
    'nav.github': 'GitHub',
    'nav.try.demo': 'Probar Demo',

    // Hero Section
    'hero.hackathon.participating': 'Participando en',
    'hero.hackathon.link': 'Midnight Hackathon – Buenos Aires',
    'hero.title': 'Tu Identidad',
    'hero.title.highlight': 'Completamente',
    'hero.title.end': 'Protegida',
    'hero.subtitle': 'Control total sobre tus datos personales con tecnología Zero-Knowledge. Comparte información sin comprometer tu privacidad.',
    'hero.feature.1': '• Sistema de privacidad multicapa (niveles 0–6)',
    'hero.feature.2': '• Demo interactiva con simulación',
    'hero.cta.demo': 'Probar Demo',
    'hero.cta.waitlist': 'Unirse a Lista de Espera',

    // Privacy Levels
    'privacy.title': 'Sistema de Privacidad Multicapa',
    'privacy.subtitle': 'Controla exactamente qué información compartes y con quién a través de nuestro sistema de niveles.',
    'privacy.explore.hint': '👆 En móvil, desliza horizontalmente para explorar todos los niveles.',
    'privacy.detail.prefix': 'Detalle del nivel',
    'privacy.level.0.title': 'Nivel 0 - Información Confidencial Absoluta',
    'privacy.level.0.subtitle': 'Solo el usuario; nunca compartida',
    'privacy.level.0.access': 'Solo el usuario; nunca compartida.',
    'privacy.level.0.examples': 'Historial médico completo, llaves privadas, documentos de identidad en crudo.',
    'privacy.level.0.security': 'Cifrado total y almacenado en bóveda privada. Ninguna API o tercero puede acceder.',
    'privacy.level.1.title': 'Nivel 1 - Información Sensible',
    'privacy.level.1.subtitle': 'Verificación crítica con consentimiento explícito',
    'privacy.level.1.access': 'Compartida solo en casos de verificación crítica con consentimiento explícito.',
    'privacy.level.1.examples': 'Resultados médicos específicos, datos financieros sensibles (cuentas, tarjetas).',
    'privacy.level.1.security': 'Puede otorgarse acceso temporal y auditado.',
    'privacy.level.2.title': 'Nivel 2 - Información Privada',
    'privacy.level.2.subtitle': 'Compartición selectiva con usuarios/organizaciones autorizadas',
    'privacy.level.2.access': 'Compartida de forma selectiva con usuarios/organizaciones autorizadas.',
    'privacy.level.2.examples': 'Dirección, teléfono, historial laboral o académico.',
    'privacy.level.2.security': 'Encriptada; solo revelada a partes verificadas y con permisos de nivel adecuado.',
    'privacy.level.3.title': 'Nivel 3 - Información Interna',
    'privacy.level.3.subtitle': 'Interacciones internas bajo acuerdos de privacidad',
    'privacy.level.3.access': 'Usada para interacciones internas dentro de servicios o empresas, bajo acuerdos de privacidad.',
    'privacy.level.3.examples': 'Evaluaciones internas, datos no públicos de seguros, reportes no sensibles.',
    'privacy.level.3.security': 'Acceso regulado, con trazabilidad y auditoría.',
    'privacy.level.4.title': 'Nivel 4 - Información Pública Controlada',
    'privacy.level.4.subtitle': 'Visible parcialmente al público o en contextos de confianza',
    'privacy.level.4.access': 'Información que puede hacerse visible parcialmente al público o en contextos de confianza.',
    'privacy.level.4.examples': 'Perfil profesional, certificados públicos, información que el usuario quiera compartir en redes controladas.',
    'privacy.level.4.security': 'Control sobre qué partes son visibles y a quién.',
    'privacy.level.5.title': 'Nivel 5 - ZK Data (Zero-Knowledge Proofs)',
    'privacy.level.5.subtitle': 'Verificar atributos sin exponer información real',
    'privacy.level.5.access': 'Uso de pruebas criptográficas ZK para verificar atributos sin exponer la información real.',
    'privacy.level.5.examples': 'Verificación de que eres mayor de 18 sin revelar tu fecha de nacimiento, prueba de cobertura de seguro sin mostrar la póliza completa.',
    'privacy.level.5.security': 'Máxima privacidad; datos nunca se revelan, solo se prueba el atributo.',
    'privacy.level.6.title': 'Nivel 6 - Ecosystem Applications',
    'privacy.level.6.subtitle': 'Aplicaciones sobre infraestructura IDShield',
    'privacy.level.6.access': 'Empresas y desarrolladores pueden construir aplicaciones sobre la infraestructura de IDShield, usando datos en forma modular y controlada.',
    'privacy.level.6.examples': 'Aplicaciones médicas, seguros, identidad digital, gobernanza.',
    'privacy.level.6.security': 'El usuario sigue siendo el dueño de los datos y aprueba cada uso; IDShield monetiza a través de APIs/licencias en este nivel.',
    'privacy.labels.access': 'Acceso',
    'privacy.labels.examples': 'Ejemplos',
    'privacy.labels.security': 'Seguridad',

    // Use Cases
    'cases.title': 'Casos de Uso',
    'cases.subtitle': 'IDShield transforma la gestión de identidad digital en múltiples sectores',
    'cases.health.title': 'Salud Digital',
    'cases.health.description': 'Comparte información médica necesaria sin exponer tu historial completo. Ideal para seguros de salud y consultas médicas.',
    'cases.health.compliance': 'HIPAA Compliant',
    'cases.insurance.title': 'Seguros',
    'cases.insurance.description': 'Verifica tu elegibilidad para seguros sin revelar información financiera sensible. Proceso de suscripción más rápido y privado.',
    'cases.insurance.verification': 'Verificación Instant',
    'cases.government.title': 'Gobierno & Educación',
    'cases.government.description': 'Accede a servicios gubernamentales y educativos verificando solo la información necesaria. Privacidad garantizada en trámites oficiales.',
    'cases.government.compliance': 'Cumple Regulaciones',

    // How It Works
    'how.title': 'Cómo Funciona IDShield',
    'how.subtitle': 'Protege tu identidad en tres simples pasos con tecnología blockchain avanzada.',
    'how.step.1.title': 'Conecta tu Wallet',
    'how.step.1.description': 'Vincula tu wallet Lace para acceder a IDShield y firmar permisos.',
    'how.step.2.title': 'Organiza tus Datos',
    'how.step.2.description': 'Guarda tu información en 7 niveles (0–6), desde privacidad absoluta hasta ecosistema.',
    'how.step.3.title': 'Genera Pruebas ZK',
    'how.step.3.description': 'Comparte atributos verificables sin revelar datos crudos (p. ej., alergias o cobertura activa).',
    'how.example.title': 'Ejemplo de Uso',
    'how.example.subtitle': 'Flujo Paciente–Doctor (con permisos y auditoría)',
    'how.example.request': 'Solicitud: el consultorio pide "lectura Nivel 1 y 2" (alergias, diagnósticos previos).',
    'how.example.request.scope': 'Se especifica alcance + tiempo (ej. 24 h).',
    'how.example.auth': 'Autorización: aprobás en tu wallet y se registra en contratos Midnight.',
    'how.example.auth.revoke': 'Revocable en cualquier momento.',
    'how.example.record': 'Registro: el médico carga la evolución y se guarda un hash + metadatos auditables.',
    'how.example.record.privacy': 'Sin exponer tus datos de Nivel 0.',
    'how.example.badge.1': '✓ Lectura controlada por niveles',
    'how.example.badge.2': '✓ ZK para atributos (alergias, cobertura)',
    'how.example.badge.3': '✓ Auditoría y revocación',

    // Contact
    'contact.title': 'Únete al Futuro de la Privacidad',
    'contact.subtitle': 'Sé parte de la revolución en protección de datos personales. Regístrate para early access.',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Email',
    'contact.form.message': 'Interés Principal',
    'contact.form.interest.placeholder': 'Selecciona tu interés principal',
    'contact.form.interest.personal': 'Uso Personal',
    'contact.form.interest.development': 'Desarrollo de Apps',
    'contact.form.interest.enterprise': 'Integración Empresarial',
    'contact.form.interest.research': 'Investigación',
    'contact.form.submit': 'Unirse a Lista de Espera',
    'contact.form.loading': 'Procesando...',
    'contact.form.privacy': 'Al registrarte, aceptas nuestros términos de privacidad. No spam, prometido.',
    'contact.benefits.1': 'Control total de tus datos',
    'contact.benefits.2': 'Tecnología Zero-Knowledge',
    'contact.benefits.3': 'Integración con Cardano',
    'contact.benefits.4': 'Marketplace de apps verificadas',

    // Footer
    'footer.description': 'Protegiendo tu identidad digital con tecnología blockchain avanzada y pruebas Zero-Knowledge.',
    'footer.product': 'Producto',
    'footer.support': 'Soporte',
    'footer.features': 'Características',
    'footer.security': 'Seguridad',
    'footer.integration': 'Integración',
    'footer.api': 'API Docs',
    'footer.documentation': 'Documentación',
    'footer.help': 'Ayuda',
    'footer.contact': 'Contacto',
    'footer.status': 'Estado',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2025 IDShield es una marca de',
    'footer.rights': '. Todos los derechos reservados.',
    'footer.hackathon': 'Producto creado para el hackathon Midnight Buenos Aires',
    'footer.coming.soon': 'Próximamente',

    // Waitlist Modal
    'waitlist.title': 'Únete a la Lista de Espera',
    'waitlist.subtitle': 'Sé de los primeros en acceder a IDShield cuando esté disponible.',
    'waitlist.form.name': 'Nombre completo',
    'waitlist.form.email': 'Correo electrónico',
    'waitlist.form.company': 'Empresa (opcional)',
    'waitlist.form.interest': 'Área de interés',
    'waitlist.form.interest.health': 'Salud Digital',
    'waitlist.form.interest.insurance': 'Seguros',
    'waitlist.form.interest.government': 'Gobierno',
    'waitlist.form.interest.education': 'Educación',
    'waitlist.form.interest.other': 'Otro',
    'waitlist.form.submit': 'Unirse a Lista de Espera',
    'waitlist.success': '¡Gracias! Te hemos agregado a la lista de espera.',
    'waitlist.error': 'Error al enviar. Inténtalo de nuevo.',

    // Privacy Policy
    'privacy.page.title': 'IDShield – Términos de Privacidad y Protección de Datos',
    'privacy.page.effective': 'Fecha de vigencia: 24 de agosto de 2025',
    'privacy.page.tagline': 'Tu Privacidad, Tu Control',
    'privacy.page.intro': 'IDShield está diseñado para darte control total sobre tu información personal. Todos los datos que eliges compartir están cifrados y, cuando corresponde, asegurados con pruebas Zero-Knowledge (ZK). Nunca accedemos a tus datos privados sin procesar.',
    'privacy.page.collect.title': 'Qué Datos Recopilamos',
    'privacy.page.collect.voluntary': 'Información voluntaria: Dirección de wallet (ej. Lace), email (si te unes a nuestra lista de espera), y preferencias que proporciones.',
    'privacy.page.collect.usage': 'Datos de uso: Análisis no identificables como visitas a páginas y patrones de interacción, recopilados solo para mejorar nuestro sitio.',
    'privacy.page.use.title': 'Cómo se Utilizan tus Datos',
    'privacy.page.use.operate': 'Para operar y mostrar la demo de IDShield.',
    'privacy.page.use.communicate': 'Para comunicarnos contigo si optas por nuestra lista de espera o eventos.',
    'privacy.page.use.compliance': 'Para asegurar cumplimiento con requisitos de hackathon o legales.',
    'privacy.page.not.title': 'Lo Que No Hacemos',
    'privacy.page.not.sell': 'No vendemos, rentamos o intercambiamos tus datos.',
    'privacy.page.not.share': 'No compartimos información personal con terceros sin tu consentimiento explícito.',
    'privacy.page.not.store': 'No almacenamos registros sensibles (como datos de salud o seguros) en nuestro sitio de entrada; esos son controlados por ti dentro de la bóveda descentralizada de IDShield.',
    'privacy.page.security.title': 'Seguridad',
    'privacy.page.security.description': 'Utilizamos cifrado estándar de la industria y mecanismos ZK para asegurar privacidad por diseño. Cualquier prueba generada a través de la demo es simulada y no expone datos personales reales.',
    'privacy.page.rights.title': 'Tus Derechos',
    'privacy.page.rights.description': 'Puedes solicitar acceso o eliminación de cualquier información que proporciones (como tu email) en cualquier momento contactándonos a: contact@idshield.cc',
    'privacy.page.third.title': 'Servicios de Terceros',
    'privacy.page.third.description': 'Si nuestro sitio de entrada utiliza análisis (ej. herramientas que respetan la privacidad), las cookies son mínimas y solo para funcionalidad esencial. Puedes optar por no participar cuando sea aplicable.',
    'privacy.page.updates.title': 'Actualizaciones',
    'privacy.page.updates.description': 'Podemos actualizar estos términos conforme evolucionan nuestros servicios. Los cambios se publicarán aquí con una fecha actualizada.',
    'privacy.page.contact.info': 'Contacto: Para preguntas o inquietudes sobre tu privacidad, envíanos un email a contact@idshield.cc',

    // Terms & Conditions
    'terms.page.title': 'IDShield – Términos y Condiciones',
    'terms.page.effective': 'Fecha de vigencia: 24 de agosto de 2025',
    'terms.page.acceptance.title': '1. Aceptación de Términos',
    'terms.page.acceptance.description': 'Al acceder o utilizar la página de IDShield, demo o servicios, aceptas estos Términos y Condiciones y nuestra Política de Privacidad. Si no estás de acuerdo, por favor no uses nuestro sitio o demo.',
    'terms.page.purpose.title': '2. Propósito del Sitio',
    'terms.page.purpose.intro': 'Esta página está destinada a:',
    'terms.page.purpose.info': 'Proporcionar información sobre IDShield y sus características.',
    'terms.page.purpose.demo': 'Mostrar una demo de nuestra tecnología de privacidad Zero-Knowledge.',
    'terms.page.purpose.waitlist': 'Permitir a los visitantes unirse a una lista de espera o solicitar actualizaciones.',
    'terms.page.purpose.disclaimer': 'La demo e información proporcionadas son solo para fines de demostración y educativos. No constituyen asesoramiento legal, médico o financiero.',
    'terms.page.eligibility.title': '3. Elegibilidad',
    'terms.page.eligibility.description': 'Nuestros servicios están disponibles para personas de 18 años o más. Al usar nuestro sitio, confirmas que cumples este requisito.',
    'terms.page.responsibilities.title': '4. Responsabilidades del Usuario',
    'terms.page.responsibilities.lawful': 'Aceptas usar nuestro sitio y demo de manera legal y respetuosa.',
    'terms.page.responsibilities.hack': 'No intentes hackear, interrumpir o usar incorrectamente la demo o la infraestructura del sitio.',
    'terms.page.responsibilities.info': 'Eres responsable de cualquier información que proporciones voluntariamente (ej. email para lista de espera).',
    'terms.page.intellectual.title': '5. Propiedad Intelectual',
    'terms.page.intellectual.description': 'Todo el contenido en este sitio, incluyendo logos, diseños, gráficos y texto, es propiedad de IDShield o sus licenciantes. No puedes copiar, reproducir o distribuir sin nuestro consentimiento previo por escrito.',
    'terms.page.thirdparty.title': '6. Enlaces de Terceros',
    'terms.page.thirdparty.description': 'Nuestro sitio puede incluir enlaces a sitios o servicios de terceros (ej. socios de hackathon). No somos responsables de su contenido o prácticas.',
    'terms.page.warranties.title': '7. Descargo de Garantías',
    'terms.page.warranties.description': 'La demo de IDShield se proporciona "tal como está", sin garantías de ningún tipo, expresas o implícitas. No garantizamos servicio ininterrumpido o libre de errores, ni garantizamos resultados específicos del uso de la demo.',
    'terms.page.liability.title': '8. Limitación de Responsabilidad',
    'terms.page.liability.intro': 'En la máxima medida permitida por la ley:',
    'terms.page.liability.damages': 'IDShield no es responsable de ningún daño, directo o indirecto, resultante del uso de nuestra página o demo.',
    'terms.page.liability.data': 'Cualquier dato usado en la demo es ilustrativo; las decisiones médicas o de seguros reales no deben basarse en las salidas de la demo.',
    'terms.page.changes.title': '9. Cambios en los Términos',
    'terms.page.changes.description': 'Podemos actualizar estos Términos de vez en cuando. Las actualizaciones se publicarán aquí con una nueva fecha de vigencia. Tu uso continuo de nuestro sitio después de los cambios significa que aceptas los términos actualizados.',
    'terms.page.governing.title': '10. Ley Aplicable',
    'terms.page.governing.description': 'Estos Términos se rigen por las leyes de Argentina. Cualquier disputa se resolverá en los tribunales competentes de Buenos Aires, Argentina.',
    'terms.page.contact.title': '11. Contáctanos',
    'terms.page.contact.description': 'Para preguntas sobre estos Términos, contacta: contact@idshield.cc',

    // ACE Framework
    'ace.title': 'Framework',
    'ace.title.highlight': 'ACE',
    'ace.title.end': 'de Libertad',
    'ace.subtitle': 'IDShield está alineado con el',
    'ace.subtitle.challenge': 'ACE Freedom Challenge',
    'ace.subtitle.hackathon': 'del Midnight Hackathon Buenos Aires: protegemos',
    'ace.subtitle.components': 'usando ZK y contratos privados en Midnight.',
    'ace.association.title': 'Association',
    'ace.association.description': 'Conexiones privadas y membresías verificadas con ZK en bóvedas de datos compartidas.',
    'ace.association.example': 'Ej.: grupos médicos/aseguradoras con acceso mínimo necesario.',
    'ace.commerce.title': 'Commerce',
    'ace.commerce.description': 'Transacciones/validaciones privadas con',
    'ace.commerce.description.highlight': 'divulgación selectiva',
    'ace.commerce.description.end': 'y control de permisos.',
    'ace.commerce.example': 'Ej.: póliza activa o solvencia sin revelar el documento completo.',
    'ace.expression.title': 'Expression',
    'ace.expression.description': 'Publicaciones, encuestas y credenciales anónimas con pruebas verificables.',
    'ace.expression.example': 'Ej.: atestaciones anónimas con prueba de elegibilidad.',
    'ace.coverage.title': 'Cobertura del Midnight Hackathon Buenos Aires',
    'ace.coverage.description': 'Cumplimos con los',
    'ace.coverage.tracks': '3 tracks ACE',
    'ace.coverage.components': '≥ 2 componentes requeridos',
    'ace.coverage.description.end': '.',
    'ace.zk.verification': 'ZK Verification:',
    'ace.zk.description': 'pruebas de atributos (edad, póliza, membresía).',
    'ace.secure.sharing': 'Secure Data Sharing:',
    'ace.secure.description': 'divulgación selectiva y revocación.',
    'ace.openzeppelin.integration': 'OpenZeppelin Integration:',
    'ace.openzeppelin.description': 'roles/pausable & contratos seguros.',
    'ace.developer.tooling': 'Developer Tooling:',
    'ace.developer.description': 'generador/CLI para flujos ZK (demo).',
    'ace.cta.demo': 'Probar Demo',
    'ace.demo.description': 'La demo simula conexión Lace y generación de pruebas ZK.',
  },
  en: {
    // Navigation
    'nav.privacy.levels': 'Privacy Levels',
    'nav.demo': 'Try Demo',
    'nav.use.cases': 'Use Cases',
    'nav.ace.framework': 'ACE Framework',
    'nav.github': 'GitHub',
    'nav.try.demo': 'Try Demo',

    // Hero Section
    'hero.hackathon.participating': 'Participating in',
    'hero.hackathon.link': 'Midnight Hackathon – Buenos Aires',
    'hero.title': 'Your Identity',
    'hero.title.highlight': 'Completely',
    'hero.title.end': 'Protected',
    'hero.subtitle': 'Total control over your personal data with Zero-Knowledge technology. Share verifiable information without compromising your privacy.',
    'hero.feature.1': '• Multi-layer privacy system (levels 0–6)',
    'hero.feature.2': '• Interactive demo with simulation',
    'hero.cta.demo': 'Try Demo',
    'hero.cta.waitlist': 'Join Waitlist',

    // Privacy Levels
    'privacy.title': 'Multi-Layer Privacy System',
    'privacy.subtitle': 'Control exactly what information you share and with whom through our level system.',
    'privacy.explore.hint': '👆 On mobile, swipe horizontally to explore all levels.',
    'privacy.detail.prefix': 'Level detail',
    'privacy.level.0.title': 'Level 0 - Absolute Confidential Information',
    'privacy.level.0.subtitle': 'User only; never shared',
    'privacy.level.0.access': 'User only; never shared.',
    'privacy.level.0.examples': 'Complete medical history, private keys, raw identity documents.',
    'privacy.level.0.security': 'Total encryption and stored in private vault. No API or third party can access.',
    'privacy.level.1.title': 'Level 1 - Sensitive Information',
    'privacy.level.1.subtitle': 'Critical verification with explicit consent',
    'privacy.level.1.access': 'Shared only in cases of critical verification with explicit consent.',
    'privacy.level.1.examples': 'Specific medical results, sensitive financial data (accounts, cards).',
    'privacy.level.1.security': 'Temporary and audited access can be granted.',
    'privacy.level.2.title': 'Level 2 - Private Information',
    'privacy.level.2.subtitle': 'Selective sharing with authorized users/organizations',
    'privacy.level.2.access': 'Shared selectively with authorized users/organizations.',
    'privacy.level.2.examples': 'Address, phone, work or academic history.',
    'privacy.level.2.security': 'Encrypted; only revealed to verified parties with appropriate level permissions.',
    'privacy.level.3.title': 'Level 3 - Internal Information',
    'privacy.level.3.subtitle': 'Internal interactions under privacy agreements',
    'privacy.level.3.access': 'Used for internal interactions within services or companies, under privacy agreements.',
    'privacy.level.3.examples': 'Internal evaluations, non-public insurance data, non-sensitive reports.',
    'privacy.level.3.security': 'Regulated access, with traceability and auditing.',
    'privacy.level.4.title': 'Level 4 - Controlled Public Information',
    'privacy.level.4.subtitle': 'Partially visible to public or in trusted contexts',
    'privacy.level.4.access': 'Information that can be made partially visible to the public or in trusted contexts.',
    'privacy.level.4.examples': 'Professional profile, public certificates, information the user wants to share on controlled networks.',
    'privacy.level.4.security': 'Control over which parts are visible and to whom.',
    'privacy.level.5.title': 'Level 5 - ZK Data (Zero-Knowledge Proofs)',
    'privacy.level.5.subtitle': 'Verify attributes without exposing real information',
    'privacy.level.5.access': 'Use of ZK cryptographic proofs to verify attributes without exposing real information.',
    'privacy.level.5.examples': 'Verification that you are over 18 without revealing your birth date, proof of insurance coverage without showing the complete policy.',
    'privacy.level.5.security': 'Maximum privacy; data is never revealed, only the attribute is proven.',
    'privacy.level.6.title': 'Level 6 - Ecosystem Applications',
    'privacy.level.6.subtitle': 'Applications on IDShield infrastructure',
    'privacy.level.6.access': 'Companies and developers can build applications on IDShield infrastructure, using data in modular and controlled form.',
    'privacy.level.6.examples': 'Medical applications, insurance, digital identity, governance.',
    'privacy.level.6.security': 'User remains the owner of data and approves each use; IDShield monetizes through APIs/licenses at this level.',
    'privacy.labels.access': 'Access',
    'privacy.labels.examples': 'Examples',
    'privacy.labels.security': 'Security',

    // Use Cases
    'cases.title': 'Use Cases',
    'cases.subtitle': 'IDShield transforms digital identity management across multiple sectors',
    'cases.health.title': 'Digital Health',
    'cases.health.description': 'Share necessary medical information without exposing your complete history. Ideal for health insurance and medical consultations.',
    'cases.health.compliance': 'HIPAA Compliant',
    'cases.insurance.title': 'Insurance',
    'cases.insurance.description': 'Verify your eligibility for insurance without revealing sensitive financial information. Faster and more private underwriting process.',
    'cases.insurance.verification': 'Instant Verification',
    'cases.government.title': 'Government & Education',
    'cases.government.description': 'Access government and educational services by verifying only necessary information. Guaranteed privacy in official procedures.',
    'cases.government.compliance': 'Regulation Compliant',

    // How It Works
    'how.title': 'How IDShield Works',
    'how.subtitle': 'Protect your identity in three simple steps with advanced blockchain technology.',
    'how.step.1.title': 'Connect your Wallet',
    'how.step.1.description': 'Link your Lace wallet to access IDShield and sign permissions.',
    'how.step.2.title': 'Organize your Data',
    'how.step.2.description': 'Store your information in 7 levels (0–6), from absolute privacy to ecosystem.',
    'how.step.3.title': 'Generate ZK Proofs',
    'how.step.3.description': 'Share verifiable attributes without revealing raw data (e.g., allergies or active coverage).',
    'how.example.title': 'Use Case Example',
    'how.example.subtitle': 'Patient–Doctor Flow (with permissions and audit)',
    'how.example.request': 'Request: the clinic requests "Level 1 and 2 read" (allergies, previous diagnoses).',
    'how.example.request.scope': 'Scope + time specified (e.g. 24 h).',
    'how.example.auth': 'Authorization: you approve in your wallet and it\'s registered in Midnight contracts.',
    'how.example.auth.revoke': 'Revocable at any time.',
    'how.example.record': 'Record: doctor uploads the evolution and a hash + auditable metadata is saved.',
    'how.example.record.privacy': 'Without exposing your Level 0 data.',
    'how.example.badge.1': '✓ Level-controlled reading',
    'how.example.badge.2': '✓ ZK for attributes (allergies, coverage)',
    'how.example.badge.3': '✓ Audit and revocation',

    // Contact
    'contact.title': 'Join the Future of Privacy',
    'contact.subtitle': 'Be part of the revolution in personal data protection. Sign up for early access.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Main Interest',
    'contact.form.interest.placeholder': 'Select your main interest',
    'contact.form.interest.personal': 'Personal Use',
    'contact.form.interest.development': 'App Development',
    'contact.form.interest.enterprise': 'Enterprise Integration',
    'contact.form.interest.research': 'Research',
    'contact.form.submit': 'Join Waitlist',
    'contact.form.loading': 'Processing...',
    'contact.form.privacy': 'By signing up, you agree to our privacy terms. No spam, promised.',
    'contact.benefits.1': 'Total control of your data',
    'contact.benefits.2': 'Zero-Knowledge Technology',
    'contact.benefits.3': 'Cardano Integration',
    'contact.benefits.4': 'Verified app marketplace',
    
    // ACE Framework
    'ace.title': 'Framework',
    'ace.title.highlight': 'ACE',
    'ace.title.end': 'for Freedom',
    'ace.subtitle': 'IDShield is aligned with the',
    'ace.subtitle.challenge': 'ACE Freedom Challenge',
    'ace.subtitle.hackathon': 'of Midnight Hackathon Buenos Aires: we protect',
    'ace.subtitle.components': 'using ZK and private contracts on Midnight.',
    'ace.association.title': 'Association',
    'ace.association.description': 'Private connections and verified memberships with ZK in shared data vaults.',
    'ace.association.example': 'Ex.: medical groups/insurers with minimum necessary access.',
    'ace.commerce.title': 'Commerce',
    'ace.commerce.description': 'Private transactions/validations with',
    'ace.commerce.description.highlight': 'selective disclosure',
    'ace.commerce.description.end': 'and permission control.',
    'ace.commerce.example': 'Ex.: active policy or solvency without revealing complete document.',
    'ace.expression.title': 'Expression',
    'ace.expression.description': 'Anonymous publications, surveys and credentials with verifiable proofs.',
    'ace.expression.example': 'Ex.: anonymous attestations with proof of eligibility.',
    'ace.coverage.title': 'Midnight Hackathon Buenos Aires Coverage',
    'ace.coverage.description': 'We comply with the',
    'ace.coverage.tracks': '3 ACE tracks',
    'ace.coverage.components': '≥ 2 required components',
    'ace.coverage.description.end': '.',
    'ace.zk.verification': 'ZK Verification:',
    'ace.zk.description': 'attribute proofs (age, policy, membership).',
    'ace.secure.sharing': 'Secure Data Sharing:',
    'ace.secure.description': 'selective disclosure and revocation.',
    'ace.openzeppelin.integration': 'OpenZeppelin Integration:',
    'ace.openzeppelin.description': 'roles/pausable & secure contracts.',
    'ace.developer.tooling': 'Developer Tooling:',
    'ace.developer.description': 'generator/CLI for ZK flows (demo).',
    'ace.cta.demo': 'Try Demo',
    'ace.demo.description': 'The demo simulates Lace connection and ZK proof generation.',

    // Footer
    'footer.description': 'Protecting your digital identity with advanced blockchain technology and Zero-Knowledge proofs.',
    'footer.product': 'Product',
    'footer.support': 'Support',
    'footer.features': 'Features',
    'footer.security': 'Security',
    'footer.integration': 'Integration',
    'footer.api': 'API Docs',
    'footer.documentation': 'Documentation',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.status': 'Status',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2025 IDShield is a trademark of',
    'footer.rights': '. All rights reserved.',
    'footer.hackathon': 'Product created for the Midnight Buenos Aires hackathon',
    'footer.coming.soon': 'Coming Soon',

    // Waitlist Modal
    'waitlist.title': 'Join the Waitlist',
    'waitlist.subtitle': 'Be among the first to access IDShield when it becomes available.',
    'waitlist.form.name': 'Full name',
    'waitlist.form.email': 'Email address',
    'waitlist.form.company': 'Company (optional)',
    'waitlist.form.interest': 'Area of interest',
    'waitlist.form.interest.health': 'Digital Health',
    'waitlist.form.interest.insurance': 'Insurance',
    'waitlist.form.interest.government': 'Government',
    'waitlist.form.interest.education': 'Education',
    'waitlist.form.interest.other': 'Other',
    'waitlist.form.submit': 'Join Waitlist',
    'waitlist.success': 'Thank you! We\'ve added you to the waitlist.',
    'waitlist.error': 'Error sending. Please try again.',

    // Privacy Policy
    'privacy.page.title': 'IDShield – Privacy & Data Protection Terms',
    'privacy.page.effective': 'Effective Date: August 24, 2025',
    'privacy.page.tagline': 'Your Privacy, Your Control',
    'privacy.page.intro': 'IDShield is designed to give you full control over your personal information. All data you choose to share is encrypted and, where applicable, secured with Zero-Knowledge proofs (ZK). We never access your raw private data.',
    'privacy.page.collect.title': 'What Data We Collect',
    'privacy.page.collect.voluntary': 'Voluntary information: Wallet address (e.g., Lace), email (if you join our waitlist), and preferences you provide.',
    'privacy.page.collect.usage': 'Usage data: Non-identifiable analytics like page visits and interaction patterns, collected only to improve our site.',
    'privacy.page.use.title': 'How Your Data is Used',
    'privacy.page.use.operate': 'To operate and showcase the IDShield demo.',
    'privacy.page.use.communicate': 'To communicate with you if you opt into our waitlist or events.',
    'privacy.page.use.compliance': 'To ensure compliance with hackathon or legal requirements.',
    'privacy.page.not.title': 'What We Do Not Do',
    'privacy.page.not.sell': 'We do not sell, rent, or trade your data.',
    'privacy.page.not.share': 'We do not share personal information with third parties without your explicit consent.',
    'privacy.page.not.store': 'We do not store sensitive records (like health or insurance data) on our landing site; those are controlled by you inside IDShield\'s decentralized vault.',
    'privacy.page.security.title': 'Security',
    'privacy.page.security.description': 'We use industry-standard encryption and ZK mechanisms to ensure privacy by design. Any proofs generated through the demo are simulated and do not expose real personal data.',
    'privacy.page.rights.title': 'Your Rights',
    'privacy.page.rights.description': 'You can request access or deletion of any information you provide (such as your email) at any time by contacting us: contact@idshield.cc',
    'privacy.page.third.title': 'Third-Party Services',
    'privacy.page.third.description': 'If our landing page uses analytics (e.g., privacy-respecting tools), cookies are minimal and only for essential functionality. You can opt out where applicable.',
    'privacy.page.updates.title': 'Updates',
    'privacy.page.updates.description': 'We may update these terms as our services evolve. Changes will be posted here with an updated date.',
    'privacy.page.contact.info': 'Contact: For questions or concerns about your privacy, email us at contact@idshield.cc',

    // Terms & Conditions
    'terms.page.title': 'IDShield – Terms & Conditions',
    'terms.page.effective': 'Effective Date: August 24, 2025',
    'terms.page.acceptance.title': '1. Acceptance of Terms',
    'terms.page.acceptance.description': 'By accessing or using the IDShield landing page, demo, or services, you agree to these Terms & Conditions and our Privacy Policy. If you do not agree, please do not use our site or demo.',
    'terms.page.purpose.title': '2. Purpose of the Site',
    'terms.page.purpose.intro': 'This landing page is intended to:',
    'terms.page.purpose.info': 'Provide information about IDShield and its features.',
    'terms.page.purpose.demo': 'Showcase a demo of our Zero-Knowledge privacy technology.',
    'terms.page.purpose.waitlist': 'Allow visitors to join a waitlist or request updates.',
    'terms.page.purpose.disclaimer': 'The demo and information provided are for demonstration and educational purposes only. They do not constitute legal, medical, or financial advice.',
    'terms.page.eligibility.title': '3. Eligibility',
    'terms.page.eligibility.description': 'Our services are available to individuals 18 years or older. By using our site, you confirm you meet this requirement.',
    'terms.page.responsibilities.title': '4. User Responsibilities',
    'terms.page.responsibilities.lawful': 'You agree to use our site and demo lawfully and respectfully.',
    'terms.page.responsibilities.hack': 'Do not attempt to hack, disrupt, or misuse the demo or site infrastructure.',
    'terms.page.responsibilities.info': 'You are responsible for any information you voluntarily provide (e.g., email for waitlist).',
    'terms.page.intellectual.title': '5. Intellectual Property',
    'terms.page.intellectual.description': 'All content on this site, including logos, designs, graphics, and text, is the property of IDShield or its licensors. You may not copy, reproduce, or distribute it without our prior written consent.',
    'terms.page.thirdparty.title': '6. Third-Party Links',
    'terms.page.thirdparty.description': 'Our site may include links to third-party sites or services (e.g., hackathon partners). We are not responsible for their content or practices.',
    'terms.page.warranties.title': '7. Disclaimer of Warranties',
    'terms.page.warranties.description': 'The IDShield demo is provided "as is," without warranties of any kind, express or implied. We do not guarantee uninterrupted or error-free service, nor do we guarantee specific outcomes from using the demo.',
    'terms.page.liability.title': '8. Limitation of Liability',
    'terms.page.liability.intro': 'To the maximum extent permitted by law:',
    'terms.page.liability.damages': 'IDShield is not liable for any damages, direct or indirect, resulting from your use of our landing page or demo.',
    'terms.page.liability.data': 'Any data used in the demo is illustrative; real medical or insurance decisions should not rely on demo outputs.',
    'terms.page.changes.title': '9. Changes to Terms',
    'terms.page.changes.description': 'We may update these Terms from time to time. Updates will be posted here with a new effective date. Your continued use of our site after changes means you accept the updated terms.',
    'terms.page.governing.title': '10. Governing Law',
    'terms.page.governing.description': 'These Terms are governed by the laws of Argentina. Any disputes will be resolved in the competent courts of Buenos Aires, Argentina.',
    'terms.page.contact.title': '11. Contact Us',
    'terms.page.contact.description': 'For questions about these Terms, contact: contact@idshield.cc',
  }
};